version : '3'

services:

  php:
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    image: "${PHP_IMAGE}"
    command: "bash /entrypoint.sh"
    volumes:
      - "./compose/php/entrypoint.sh:/entrypoint.sh"
      - "${NGINX_MOUNT_DIR}:/var/www/${COMPOSE_PROJECT_NAME}"
      - "../php.ini:/usr/local/etc/php/php.ini"
      - "../xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    depends_on:
      - "mysql"
    links:
      - "mysql"
    environment:
      PHP_IDE_CONFIG: "serverName=${COMPOSE_PROJECT_NAME}"
