version : '3'

services:

  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    image: "${NGINX_IMAGE}"
    volumes:
      - "./${SRC_DIR}:/var/www/${COMPOSE_PROJECT_NAME}"
      - "./compose/nginx/conf:/etc/nginx/conf.d"
      - "./compose/nginx/ssl:/etc/nginx/ssl"
      - "./shared/nginx/logs:/var/log/nginx"
    ports:
      - "80:80"
    links:
      - "php"
    environment:
      - COMPOSE_PROJECT_NAME
      - SRC_DOCUMENT_ROOT
      - APP_PATH