version : '3'

services:

  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    image: "${NGINX_IMAGE}"
    volumes:
      - "../../../..:/var/www/${COMPOSE_PROJECT_NAME}"
      - "../../nginx/docker.conf:/etc/nginx/conf.d/${COMPOSE_PROJECT_NAME}.conf"
      - "../../../logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
    links:
      - "php"