version : '2'

services:

  nginx:
    container_name: {PROJECT_NAME}_nginx
    image: nginx:1.11
    volumes:
      - ../../../..:/var/www/{PROJECT_NAME}
      - ../../nginx/docker.conf:/etc/nginx/conf.d/{PROJECT_NAME}.conf
      - ../../../logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    links:
      - php