version : '3'

services:

  mysql:
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    image: "${MYSQL_IMAGE}"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "${COMPOSE_PROJECT_NAME}"
      MYSQL_USER: "${COMPOSE_PROJECT_NAME}"
      MYSQL_PASSWORD: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - "./${MYSQL_DATA_DIR}:/var/lib/mysql:rw"
      - "./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf"
      - "./${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d"